### ISSUE TITLE
Support to group ingress routes based on the Service.

### ISSUE THREAD

**Issue by ambatshri** [spaceuptech/space-cloud#1147]
### The problem faced currently?
Currently, we've configured 7 services and each service is having 7-8 routes. It becomes difficult to identify which routes belong to which service and on which page.

### How can we solve it?
Even tho the routes have been prefix, it would be good to have some sort of grouping of ingress routes, like filter based on the service. This would really help when we're dealing with 30+ routes.

>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by HeyItsJs** [comment]
Hey @ambatshri, there are 2 ways we can solve this:

- Add a `group` field to each ingress route. This can be provided while adding/editing an ingress route. The `group` value will be shown in the table of ingress route. There will be a filter icon in the `group` column in the table headers. The filter icon will look something like this:

![Screenshot from 2020-07-09 11-22-12](https://user-images.githubusercontent.com/24749286/87002179-aeeab180-c1d6-11ea-894c-38c99c130a78.png)

- The second option is to provide a `Filter` button in the ingress routes page. It will open up a modal like this:

![Screenshot from 2020-07-09 11-26-22](https://user-images.githubusercontent.com/24749286/87002386-1b65b080-c1d7-11ea-8807-9efa126988eb.png)

Here, the user can specify the targeted services (project and service ids)


### My thoughts

Personally I like the second option since it does not require to configure any additional field (`group` in the first case).

Which option (from the above or some other) do you find convenient?  Also, if it's the second option, then what all fields should we allow filtering on? Is it okay if we just provide filtering on the target service?

@ambatshri

**Comment by ambatshri** [comment]
The 2nd option is much better, but according to the screen shot shared i think there's no need to provide the project, cuz the user will have already selected a project at global level. The only option I could see it to filter on services. But is it possible to use other attributes from the ingress routes, like route prefix. etc.

**Comment by HeyItsJs** [comment]
Yeah. That was a quick mockup @ambatshri 

Going forward with the 2nd option. Will include these filtering options:
- Filter ingress routes by services
- Filter ingress routes by target host (coz the target might not always be a service deployed by space cloud)
- Filter ingress routes by allowed request hosts
- Filter ingress routes by the route prefix

Let me know if there is anything more to add

**Comment by YourTechBud** [comment]
Done
