### ISSUE TITLE
Store response of security webhook and query rules in state

### ISSUE THREAD

**Issue by YourTechBud** [spaceuptech/space-cloud#1268]
### The problem faced currently?
Currently we do not store the value received from the webhook in the `args` state. Because of this, we cannot use the values received from the webhook.
### How can we solve it?
Accept a `store` field in the security rule where the response body of the webhook will be saved.
>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by HeyItsJs** [comment]
@YourTechBud Do you think we should accept a `store` field for the `query` rule as well instead of directly saving the db response in `args.res`? If no `store` is provided then we can use `args.res` for backwards compatibility. What do you think?

Also, should the `store` field in the `webhook` rule be compulsory or optional? What would happen if the `store` is not specified? Would the response be not stored or would it be stored at some default place like `args.res`?

**Comment by YourTechBud** [comment]
Yes. Agreed

**Comment by HeyItsJs** [comment]
Cool @YourTechBud!

We just need to add a field `store` in case the  `rule` is `webhook` or `query`. This field needs to be optional. It specifies where the result of the database query (in case of `query`) or the webhook request (in case of `webhook`) will be stored.

Just need to make the changes in [this file](https://github.com/spaceuptech/mission-control/blob/master/src/components/security-rules/configure-rule/ConfigureRule.jsx)

Also, we need to make sure if the initial value of the `store` field is provided then it's displayed in the form.

**Comment by HeyItsJs** [comment]
Done in mission control. All thanks to @arn4v!

**Comment by YourTechBud** [comment]
Done in backend as well. Closing.
