### ISSUE TITLE
There should be a mechanism to log out of mission control

### ISSUE THREAD

**Issue by YourTechBud** [spaceuptech/space-cloud#1276]
Have a similar mechanism in team management too

>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by HeyItsJs** [comment]
Since we don't have any user's info to show in Mission Control, let's add a simple logout icon in the top bar itself rather than showing a profile avatar? @YourTechBud. In team management, we can have a different logout mechanism which is similar to the one in billing console UI. 

On clicking this logout icon in Mission Control, we can simply clear localStorage and redirect the user to the `loginURL`  returned by the `getLoginURL` function.

**Comment by HeyItsJs** [comment]
Done. Coming in `v0.19.3`.
