### ISSUE TITLE
The binary space-cloud tried to connect to spaceuptech.com

### ISSUE THREAD

**Issue by virusvn** [spaceuptech/space-cloud#209]
### Describe the bug
I download and run space-cloud binary then I received this log (I closed the lid for 10 days, so I don't know when it was):

Metrics Error - rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp: lookup spaceuptech.com on [::1]:53: server misbehaving"

It looks like the binary was trying to connect to spaceuptech.com for something?

### Expected behaviour
No connect to any outside network for any reason.

### Steps to reproduce
Couldn't reproduce but this maybe the hint:
Start the space-cloud, turn off the internet or close the laptop's lid.

### Your environment
- Space Cloud version: 0.7.1
- OS: macos 10.13.6
- The client api version (if applicable):
- Browser (if applicable):

>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

**Comment by YourTechBud** [comment]
Hey @virusvn, the `space-cloud` binary collects annonymous metrics (things like modules activated, etc.). To disable metric collection you can pass the `--disable-metrics` flag. None of your secrets (connection strings, jwt secret, etc.) are taken or monitored. @Jayesh333 we should probably document this.

The error you saw was because the gRPC connection with the server broke. But internally it reconnects automatically.

Can we close this issue if Ive addressed your concern?

**Comment by virusvn** [comment]
Hi YourTechBud,
You guys is doing awesome project, `--disable-metrics` is OK.
