### ISSUE TITLE
Remove `remove-project-scope` flag

### ISSUE THREAD

**Issue by HeyItsJs** [spaceuptech/space-cloud#497]
Right now we have implemented a quick fix for one of the weird errors MySQL was giving when database name was provided in the query. 

We should solve this problem in such a way that there should be no need of providing this flag. The table name to be used in query should be generated based on whether the user has provided the db name in the connection string rather than the value of this flag.

**Comment by YourTechBud** [comment]
@Jayesh333 i think this is an important feature to have. It's useful when the user wants to use a db name which is not the project id. Let's keep it?

**Comment by Jayesh333** [comment]
The problem with `remove-project-scope` flag as of now is that it is defined globally. Whereas, it should be defined at a database level.

And more importantly Space Cloud should be able to detect whether to remove the project scope or not without the user telling him. If the connection string contains db name then it should remove the project scope otherwise use project scope.

**Comment by Jayesh333** [comment]
After thinking for a while, I have this solution in mind:

The current implementation for `getTableName` function (and other similar functions), which is used to calculate the name of the table in the database queries is:

```go
func getTableName(project, table string, removeProjectScope bool) string {
	if removeProjectScope {
		return table
	}

	return project + "." + table
}
```

We can change its implementation to this:
```go
func getTableName(table, scope string) string {
	if scope != nil {
		table
	}

	return scope + "." + table
}
```

This `scope` will be set at the `database` level while initializing/setting the config of that database. 

**For MySQL:** While initializing we can check whether the `conn` string contains the database name or not to set the `scope` accordingly. If the database name is present in the connection string, we will set the `scope` to `nil`, so that the table name is returned in the helper functions. If the database name is not present, we will set the `scope` to `project-id`.

**New possibilities unlocked because of `scope`:**

This `scope` can prove to be a very powerful tool. For example, we can use it to configure Space Cloud to use `public` or some other `schema` in case of `Postgres`. (Right now, there is no easy way to do it). Having it as a config parameter for the database, we can now also ask the user upfront, which database or schema is he interested to use. And also allow them to change this config on the fly without requiring to re run space cloud.

**Comment by YourTechBud** [comment]
Done
