### ISSUE TITLE
GraphQL insert should allow return value of at least the id

### ISSUE THREAD

**Issue by thienpow** [spaceuptech/space-cloud#511]
<img width="913" alt="Screenshot 2019-11-19 at 2 11 13 PM" src="https://user-images.githubusercontent.com/9796623/69121351-1680af00-0ad7-11ea-8127-f1331a8657c2.png">

currently it return nothing. the only value can be returned is status.
id is important after insert in many use case of a normal app.

**Comment by YourTechBud** [comment]
This shouldn't be a very difficult since Space Cloud already generates ids internally. We can trust that the document to be inserted will have a `id` or `_id` field and return that.

However this won't work if the primary key has a different name or is not of type `ID`. @Jayesh333 what should we do?

**Comment by Jayesh333** [comment]
This is based on what I have seen people usually do to describe the fields to be returned in mutations:

```graphql
mutation {
  insert_author (docs: [{ name: "Author 1" }]) @db {
    status
    error
    returning {
      id
      name
    }
  }
}
```

This should return the following:
```graphql
{
  insert_author: {
    status: 200,
    returning: [
      { id: 1, name: "Author1" }
    ]
  }
}
```

**Comment by YourTechBud** [comment]
Coming in `v0.14.0`
