### ISSUE TITLE
Allow to create tables without security rules [default rule should be applied automatically]

### ISSUE THREAD

**Issue by s-kris** [spaceuptech/space-cloud#577]
As there is a 'default' rule in the `rules` tab, allow users to create tables without individual security rule. And that default rule should be applied automatically. 

P.S: On a related note, allow to clear rules for a table (after it is created) and save it. Again, the default rule is automatically applied.

**Comment by YourTechBud** [comment]
We already have this feature built in. @Jayesh333 we should allow the user to opt in into defining security rules for a particular table and later delete if they wish to.

**Comment by Jayesh333** [comment]
The current scenario:
- On any CRUD request, SC validates it based on the rules for the concerned table. If no rule for the requested table is found, then SC validates the request based on the default rules. If default rules are also not provided then in that case SC rejects that request with 403
- Whenever you add a database to SC via Mission control, it configures the `allow` rule as the default rule for that database
- While adding a new table via mission control, it prefils the rules for that table with `allow` rule, which can be changed later
- No option to delete the security rule of a table via mission control so that SC falls back to the default rule for that table


My proposal:

- While adding table through mission control, no security can be mentioned. SC will apply the default rules for this table as no rules are mentioned. This removes the need of solving #585. This also provides enough space in the modal to define schema.
- similarly while tracking a table, mission control doesn't configure the SC with the rules for that table, which results into default rules being applied. This solves #586 
- Option to add and remove security rules for a table from the `Rules` tab in the `Database` section

What do you think @s-kris ?

**Comment by Jayesh333** [comment]
I am assuming that most of the times, user won't be willing to change security rules while creating the table. If that's not true, then while creating table, we can have checkbox that says `Apply default security rules` which will be checked by default. If user unchecks it, then he will be provided an input to put in the security rules which again will be prefilled by the default rules.

**Comment by s-kris** [comment]
@Jayesh333 you had summarised nicely. I'm just adding to that.

1) Kindly provide checkbox thing as you mentioned. It is more elegant and better ux. 
2) Done
3) Done
<---new--->
4) Kindly look at the screenshot for making changes to `rules` tab.  
5) Use the above guidelines for `schema` tab too.
6) I suggested to increase the size of Rules/Schema input box because, it's too small in height to write complex rules/schema.
7) [Totally unrelated to this issue] Kindly remove that 'Have a Question?' floating button and add it to sidebar or give an option to show/hide it in `configure` tab. 

![Screenshot 2019-12-28 at 1 23 12 AM](https://user-images.githubusercontent.com/3975305/71530804-d2709d80-2911-11ea-84d8-ebf0393c8960.png)

**Comment by Jayesh333** [comment]
Fixed. coming in `v0.16.0`
