### ISSUE TITLE
The production (distributed) version of Realtime is still pending

### ISSUE THREAD

**Issue by YourTechBud** [spaceuptech/space-cloud#60]
We need to add kafka for the distributed realtime feature. Also we need not rely just on kafka, we can use any message broker with an at least once semantics for this task. Something like the pluggable backend for the file store module.

**Comment by joeblew99** [comment]
@YourTechBud Great idea.

I can help with a  NATS or NATS Streaming module, so users can use Kafka or NATS.

Do you guys have a gitter channel ?

**Comment by YourTechBud** [comment]
Not really. But you can join us on discord. Here's the link: https://discord.gg/ypXEEBr.

This is a super important feature and I would love to work with you to get this done!

**Comment by joeblew99** [comment]
There is a full Change Data Capture in TiDB.

**Comment by YourTechBud** [comment]
Lets not make this implementation database specific. Won't help us scale in terms of databases we support!

**Comment by joeblew99** [comment]
I was not intending to.
It was because the pattern for making it DB agnostic are there.

Here is a what i mean: https://www.cockroachlabs.com/docs/stable/change-data-capture.html

You can see all the issues and design.

We need a Unified CDC API.
Then adapters / drivers for each DB type.
We connect to their DB and so there is no need for a GRPC API on their side.
On our side a GRPC API feeding into the Queues.

**Comment by YourTechBud** [comment]
Makes sense. Would this work in a DBaaS environment (for something like AWS RDS)? We will not have access to the VM the database is running on in that case.

**Comment by YourTechBud** [comment]
Fixed
