### ISSUE TITLE
Provide(show) list of collection while adding a database event trigger

### ISSUE THREAD

**Issue by sharadregoti** [spaceuptech/space-cloud#825]
### The problem faced currently?
Current mission control doens't show tables where events can be addes we have to manually write their name in text boxes.
It would be great if MC prvoides a list of collection.

**Comment by Jayesh333** [comment]
Hey @sharadregoti, the reason why we haven't provided a list of tables is that the table field can be left empty in order to specify all tables. Also, the user might want to create an event trigger of a table he hasn't created as of now. So is it fine, if we implement an AutoComplete rather than Select box for this?

**Comment by YourTechBud** [comment]
We can have an option stating all?

**Comment by Jayesh333** [comment]
Done. Coming in `v0.17.0`
