### ISSUE TITLE
Document procedure to use istio-ingressgateway with space cloud.

### ISSUE THREAD

**Issue by aresa7796** [spaceuptech/space-cloud#934]
Why require disabled istio-ingressgateway?
istio-ingressgateway usually our core component，it is necessary to us。
How to make them coexist？

**Comment by YourTechBud** [comment]
We use space-cloud's gateway component to do all the routing. We disabled istio's default ingress gateway for our lets encrypt support.

You can use istio's ingress gateway with space cloud, however you won't be able to use the let's encrypt feature and the `routing` module (wouldn't matter since you are willing to use the ingress gateway directly). To do this.
- change the space clouds k8s service type to clusterip instead of LoadBalancer / nodeport. Need to do this since Space Cloud would take control over ports 80 and 443 otherwise
- redirect all routes with prefix `/v1/api`, `/v1/config` and `/mission-control` to SpaceCloud's gateway.

That's it.

**Comment by YourTechBud** [comment]
We should probably add this in our docs.

**Comment by YourTechBud** [comment]
Since version `0.18.0`, SC uses istio's ingress gateway by default. SC should work out of the box with vanilla Istio installations.
